### ISSUE TITLE
Where do you get the questions and their answers from?

### ISSUE THREAD

**Issue by abiusx** [ponomaREG/testMensa#1]
I looked at the source code but couldn't figure out where the test questions are coming from.

**Comment by abiusx** [comment]
https://github.com/ponomaREG/testMensa/blob/master/app/src/main/java/com/example/mensatest/Managers/Mensa.java#L22

**Comment by ponomaREG** [comment]
I just grabbed the questions from this site https://test.mensa.no/. Found the answers on some forum, it may be wrong
